io:
  output_dir: /path/to/output
  images_dir: /path/to/image_folders
  features_ID: features # need to update the configuration.py for this field?
xgboost:
  random_state: 42
  n_jobs: 12
  learning_rate: 0.2
  max_depth: 5
  weight_sensitivity: 0.0
  detritus_subsampling: false
  subsampling_percentage: 20
  num_trees_CV: 500
