io:
  output_dir: /path/to/output
  images_dir: /path/to/image_folders 
  features_ID: features # name of the training set if it exits. If it does not exist, it will be the name of the training set that will be created and saved.
  test_set: /path/to/test_set # can be kept as it is if there is no need for an evaluation
  model: /path/to/model # can be kept as it is if there is no need for an evaluation or if you train AND evaluate, it will be generated automatically.
instrument:
  uvp_pixel_threshold: 20 # usually between 20 and 22
xgboost:
  random_state: 42
  n_jobs: 12
  learning_rate: 0.2
  max_depth: 5
  weight_sensitivity: 0.0
  detritus_subsampling: false
  subsampling_percentage: 20
  num_trees_CV: 500
language:
  use_C: true
process:
  evaluate_only: false
  train_only: false
